export const ACTIVITY_TYPES = {
  PROJECT: "PROJECT",
  INTERNAL: "INTERNAL",
  ASSIGNMENT: "ASSIGNMENT",
  QUIZ: "QUIZ",
  CERTIFICATE: "CERTIFICATE",
  LAB_ENTRY: "LAB_ENTRY",
  LAB_EXIT: "LAB_EXIT",
  ATTENDANCE: "ATTENDANCE",
  REMARK: "REMARK",
  WARNING: "WARNING",
};